### ISSUE TITLE
VPR Dreadwinder

### ISSUE THREAD

**Issue by Clueless-AI** [Rabalaba/Rabbs-Rotations-for-Rotation-Solver#1]
Hello Rabb,
1st of all thanks for supporing viper, I was wondering if its possible to fix the fact that Dreadwinder isn't driftedn, a lot of times during the rotation with full uptime, it chooses to go into reawaken burst while having 2 stacks of Dreadwinder.

**Comment by Rabalaba** [comment]
It is, unfortunately it will take some time as the code it getting rather complicated at this point and once change can make 17 problems so I need to think how I will implement.

**Comment by Rabalaba** [comment]
adding (DreadwinderPvE.Cooldown.CurrentCharges == 0 || (DreadwinderPvE.Cooldown.CurrentCharges == 1 && DreadwinderPvE.Cooldown.RecastTimeRemainOneCharge > 10)) to reawaken conditions

**Comment by Rabalaba** [comment]
in next release it will check if less than 10 seconds before cap on charges or if already capped on charges it won't reawaken
