### ISSUE TITLE
PCT wont use retribution of the madeen

### ISSUE THREAD

**Issue by fpcompany** [Rabalaba/Rabbs-Rotations-for-Rotation-Solver#2]
Hey!
Bobross does not use retribution of the madeen at all and this stalls all further creature motif rotations. You have to press it manually and it continues as usual, until next retribution.

**Comment by Rabalaba** [comment]
I don't have PCT to 100 yet, I can try a fix but not sure if it will work

**Comment by Rabalaba** [comment]
pushed a fix, may work I'll wait and see

**Comment by fpcompany** [comment]
It works ty!
