### ISSUE TITLE
Current bard issues

### ISSUE THREAD

**Issue by Dubsys** [Rabalaba/Rabbs-Rotations-for-Rotation-Solver#3]
Openers attached:
![image](https://github.com/user-attachments/assets/732cf8a2-eddd-452d-8b51-250a888c8cba)
![image](https://github.com/user-attachments/assets/000ebfea-22d4-4424-8007-0415ff444c5e)

Burst Windows attached:
![image](https://github.com/user-attachments/assets/d1e6a901-842e-48f6-9a7b-09aacf80b688)
![image](https://github.com/user-attachments/assets/70a77e29-e0e9-4b76-852f-1323a6d321f1)

1. Opens with Burst shot instead of a dot (is it doing the burst rotation as an opener?)
2. Seems to sometimes (more often than not) not use barrage in the 2 minute windows, this is probably a mix of the emergencyability method where it won't use it if straight shot is ready, the attackability method where it won't use it based on pitch perfect stacks, and then also checking if blast arrow is able to be used in the generalgcd method, causing it to be unable to use barrage at any time, i think
3. Seems to love weaving more than twice sometimes, not sure why.

I'm not really sure what else is around as an issue, I can provide logs over discord or something if you need them.

**Comment by Rabalaba** [comment]
Thank you for the contributions, this has been forwarded to main RSR and included in base rotations
